### ISSUE TITLE
Python app crashes occasionally on SHIFT key press.

### ISSUE THREAD

**Issue by AquaEBM** [numworks/epsilon#1970]
#### Describe the bug
I have a Python script involving repeated calls to ion.keydown in a fast loop, on quite rare occasions the python app crashes (and brings me to the main menu, without any message) right after pressing the shift key.

I don't have any screenshots as this doesn't seem to happen on the simulator.

#### To Reproduce

(This doesn't happen systematically but this is the behaviour reproducing this bug the most often for me)

1. Go to [My Numworks Workshop Page](my.numworks.com/python/aquaebm/)
2. Download onto your calculator the scripts [util.py](https://my.numworks.com/python/aquaebm/util) and [piano_bug_showcase.py](https://my.numworks.com/python/aquaebm/piano_bug_showcase) (a version of [piano.py](https://my.numworks.com/python/aquaebm/piano) which SHOULD make the bug happen more often).
3. Keep pressing the shift key each time a tile touches the leftmost black pad.
4. After a certain number of clicks (that doesn't seem to be the same each time), python crash.

#### Environment
 - Epsilon version : 19.4.0. But I've been having this issue since 19 beta
 - Platform: N0110

**Comment by FelixNumworks** [comment]
Hello, thanks a lot for your submission :)
This issue has been fixed in the version 20 of Epsilon. You can [update your calculator](https://www.numworks.com/calculator/update/) to benefit from this fix.

**Comment by AquaEBM** [comment]
Indeed, the issue seems to have been mitigated. Though, I still get occurrences of this same bug, and under the same circumstances, just way less often.

**Comment by FelixNumworks** [comment]
Oh ok, I couldn't reproduce this problem when testing version 20, but I guess I didn't try hard enough.
Thanks again for reporting this problem. We'll work on it further.

**Comment by KarineNumWorks** [comment]
Hello ! This issue has been fixed since version 22. I will close this issue but feel free to reopen it needed
