### ISSUE TITLE
+ and - not working in the browser (when developing my scripts online)

### ISSUE THREAD

**Issue by MatejTymes** [numworks/epsilon#2235]
#### Describe the bug
i'm writing a python script but pressing the + and - keys are not recognized in the web browser (while developing my scripts)

#### Screenshots
![image](https://github.com/user-attachments/assets/09522f79-ffe8-4029-a934-921acff01541)
I'm in the focus, but + and - does not zoom the graph (it does on the calculator)

#### To Reproduce
1. Open this 3d graph viewing app:
https://my.numworks.com/python/mty/draw_3d_graph
2. Pressing arrow moves the graph
3. Pressing enter/exe/ok switches into tracing mode
4. Pressing + or - does not zoom the graph
All are done via the ion.keydown(KEY_LEFT), ion.keydown(KEY_PLUS), ...

#### Expected behavior
pressing + or - should be recognized via the ion module in the browser

#### Environment
 - Epsilon version: n/a
 - The platform(s) on which the problem happens: online simulator

**Comment by RedGl0w** [comment]
This issue has been mentioned earlier (in https://github.com/numworks/epsilon/issues/1555 for instance). https://github.com/numworks/epsilon/pull/1616/commits/d0a79c2b4f046b8fa395f971395f58290dadabf1 should fix it.

**Comment by MatejTymes** [comment]
the commit/fix is 4 years old, but the issue seems to be still present

**Comment by adri1numworks** [comment]
Hi, thank you for reaching out. I created an issue internally, we will make sure keys are recognized. In addition, we are planning to allow user to load a script to the simulator, so that one will be able to use simulator's keys. 

I'll let you know once this is done

**Comment by mobluse** [comment]
A temporary solution, until more keys are supported in the emulators, could be to use Shift+Up to zoom in, Shift+Down to zoom out, Shift+Left as `(`, Shift+Right as `)`, as alternatives to the other keys. Toolbox+arrow_keys for other movements, see https://my.numworks.com/python/mobluse/anykeys

**Comment by XanderLeaDaren** [comment]
Same problem here with a Python script to emulate an RPN app, and no way to make it usable online, whereas the script is fully functional on the physical calculator:

https://my.numworks.com/python/xanderleadaren/rpn

I’m able to open a menu mapped to [Toolbox] (see screenshot below), but except from this and [shift] detected, nothing seems trigger-able…

![nw-rpn_hotkeys](https://github.com/user-attachments/assets/d170edf5-aa87-4e49-9b74-83f25b148b14)

**Comment by XanderLeaDaren** [comment]
Related: #2087 “missing simulator keys on the python workshop”

**Comment by mobluse** [comment]
More keys are working now. In the emulators on the NumWorks site in Python shell only a few buttons on your emulator’s physical keyboard work: e.g. Tab (Toolbox), Enter (EXE), Shift, Backspace, Esc (Back), Alt+x (exp), Alt+v (var), Alt+e (EE), Alt+r (sqrt), Alt+p (pi), Alt+Shift+2 (\*\*2), Alt+l (ln), Alt+o (log), ^ (power), Alt+s (sin), Alt+c (cos), Alt+t (tan), ,, ., 0-9, +, -, *, /, and the arrow keys, but of these, in ion, only Tab, Enter, Shift, Alt (Alpha), Backspace, ., 0-9, +, -, *, /, and the arrow keys work.

These can be tested here: https://my.numworks.com/python/mobluse/anykeys

Ideas for future improvements of ion in the NumWorks simulator using US/UK keyboard:

- , (comma) could be the `,` key.
- [ and ] could act as `(` (leftparenthesis) `)` (rightparenthesis) in ion.
- The Alt codes in Python shell could changed to direct key in ion, i.e. t could be `tan`, q could be `x^2`, i or j could be `i`, w could be `x^y`.
- \` or n could be the `x,n,t` key.
- = could be the `OK` key.
- ' could be the `Ans` key.
- ; or v could be the `var` key in ion. It is now Alt+v in Python shell, but this doesn't work in ion since Alt is Alpha.
- \ could be `EE` i.e. `·10^x`.
