### ISSUE TITLE
Allow access to some Ion functions from Python

### ISSUE THREAD

**Issue by instrangeland** [numworks/epsilon#797]
One of the big issues I've seen with the Python environment on the Numworks calculator is that it is missing many of the features found in other calculator based programming languages. The most glaring of those is an input function. Even this, however, would not be necessary if Python could be given access to the Keyboard functions of Ion. Some ideas of what these should be (from the Python side.):

Ion.Keyboard.checkKey( keynumber (or some other identifier) ), returns bool true if pressed, false if not.

Ion.Keyboard.getKey() returns the number of the currently pressed key

Ion.Keyboard.keyPressed() returns true if any key is pressed, false if none are.

If a python script had access to the keyboard directly, with the work already done giving it access to the screen, a quick input function could be related. This is also a necessity for any sort of Graphical based python.

**Comment by boricj** [comment]
There's some ongoing work to improve the API provided in the Python app in general (turtle module: #748, improved kandinsky module: #748, time module: #626...). As for raw key readout specifically, I think there are a couple of issues with the Emscripten platform that are being addressed (#754, #755) before that API can be implemented.

**Comment by gpotter2** [comment]
Seems it has all be done now :-)

**Comment by Ecco** [comment]
I'm going to close this issue since most of it has been addressed. Feel free to reopen specific issue if needed 😄

**Comment by boricj** [comment]
Until we have at least a `get_keys()` and a `fill_rect()` function, this issue isn't really solved. #746 is a start to fix this and is advanced enough to allow simple real-time games like Pong.

**Comment by Ecco** [comment]
Yes, but multi-topic issues are a pain in the ass, which is the main reason I closed this issue 😄 I created #925 to track the key reading function.
